CREATE TABLE `applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`jobId` int NOT NULL,
	`resumeId` int,
	`tailoredResumeContent` text,
	`coverLetterContent` text,
	`customAnswers` json,
	`submittedAt` timestamp,
	`submissionMethod` varchar(50),
	`confirmationNumber` varchar(255),
	`status` enum('draft','submitted','viewed','screening','interview_scheduled','interviewed','offer','rejected','withdrawn') DEFAULT 'draft',
	`lastStatusUpdate` timestamp,
	`nextFollowUpDate` date,
	`followUpCount` int DEFAULT 0,
	`interviewDates` json,
	`interviewNotes` text,
	`offerAmount` int,
	`offerCurrency` varchar(3),
	`rejectionReason` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `applications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `companies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`domain` varchar(255),
	`logoUrl` text,
	`industry` varchar(255),
	`size` varchar(50),
	`founded` int,
	`headquarters` text,
	`description` text,
	`mission` text,
	`values` json,
	`culture` text,
	`techStack` json,
	`recentNews` json,
	`fundingRounds` json,
	`isHiring` boolean DEFAULT false,
	`openPositions` int DEFAULT 0,
	`lastResearchedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `companies_id` PRIMARY KEY(`id`),
	CONSTRAINT `companies_name_unique` UNIQUE(`name`)
);
--> statement-breakpoint
CREATE TABLE `contacts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`companyId` int,
	`name` varchar(255) NOT NULL,
	`email` varchar(320),
	`phone` varchar(50),
	`linkedinUrl` text,
	`title` varchar(255),
	`department` varchar(100),
	`relationshipType` varchar(50),
	`connectionStrength` int,
	`lastContactedAt` timestamp,
	`contactCount` int DEFAULT 0,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `contacts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`companyId` int,
	`title` varchar(255) NOT NULL,
	`companyName` varchar(255) NOT NULL,
	`location` text,
	`jobUrl` text NOT NULL,
	`description` text,
	`platform` varchar(50),
	`postedDate` timestamp,
	`salaryMin` int,
	`salaryMax` int,
	`salaryCurrency` varchar(3) DEFAULT 'USD',
	`employmentType` varchar(50),
	`experienceLevel` varchar(50),
	`requiredSkills` json,
	`preferredSkills` json,
	`responsibilities` json,
	`benefits` json,
	`qualificationScore` int,
	`matchedSkills` json,
	`missingSkills` json,
	`status` enum('new','qualified','rejected','applied','interviewing','offer','closed') DEFAULT 'new',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `jobs_id` PRIMARY KEY(`id`)
);
