/**
 * Tailor Agent - Resume Customization
 * 
 * Responsibilities:
 * - Select best achievements for specific job
 * - Optimize keywords for ATS
 * - Reorder and emphasize relevant experience
 * - Generate job-specific resume
 */

import { invokeLLM } from "../_core/llm";
import { getModelForTask } from "../modelRouter";
import { cacheGetOrSet, cacheKey, CachePrefix, CacheTTL } from "../cache";
import type { Achievement, Job, User } from "../../drizzle/schema";

export interface TailoredResume {
  selectedAchievements: number[]; // Achievement IDs
  resumeContent: string;
  keywords: string[];
  atsScore: number; // 0-100
}

/**
 * Select best achievements for job
 */
export async function selectAchievementsForJob(
  job: Job,
  achievements: Achievement[],
  limit: number = 8
): Promise<number[]> {
  const cacheKeyStr = cacheKey(
    CachePrefix.RESUME_GENERATION,
    "select",
    job.id.toString(),
    achievements.map(a => a.id).join(",")
  );

  return cacheGetOrSet(
    cacheKeyStr,
    async () => {
      const achievementList = achievements
        .map((a, i) => {
          const xyz = a.xyzAccomplishment || `${a.action} ${a.result}`;
          return `${i + 1}. [ID: ${a.id}] ${xyz} (${a.roleTitle} at ${a.company})`;
        })
        .join("\n");

      const prompt = `Select the top ${limit} most relevant achievements for this job:

Job: ${job.title} at ${job.companyName}
Required Skills: ${(job.requiredSkills || []).join(", ")}
Description: ${job.description}

Achievements:
${achievementList}

Return the IDs of the ${limit} most relevant achievements.`;

      const response = await invokeLLM({
        model: getModelForTask("RESUME_TAILORING"),
        messages: [
          {
            role: "system",
            content: "You are an expert at tailoring resumes for specific jobs.",
          },
          { role: "user", content: prompt },
        ],
        response_format: {
          type: "json_schema",
          json_schema: {
            name: "selected_achievements",
            strict: true,
            schema: {
              type: "object",
              properties: {
                achievementIds: { type: "array", items: { type: "number" } },
              },
              required: ["achievementIds"],
              additionalProperties: false,
            },
          },
        },
      });

      const content = String(response.choices[0]?.message?.content || "{}");
      const parsed = JSON.parse(content);
      return parsed.achievementIds.slice(0, limit);
    },
    CacheTTL.RESUME_GENERATION
  );
}

/**
 * Generate tailored resume
 */
export async function generateTailoredResume(
  user: User,
  job: Job,
  achievements: Achievement[]
): Promise<TailoredResume> {
  // Select best achievements
  const selectedIds = await selectAchievementsForJob(job, achievements);
  const selectedAchievements = achievements.filter((a) => selectedIds.includes(a.id));

  // Generate resume content
  const resumeContent = `# ${user.name || "Your Name"}
${user.email || ""}
${user.currentRole ? `## ${user.currentRole}` : ""}

## Target Role
${job.title} at ${job.companyName}

## Professional Experience

${selectedAchievements
  .map((a) => {
    const xyz = a.xyzAccomplishment || `${a.action} ${a.result}`;
    return `### ${a.roleTitle || "Role"} at ${a.company || "Company"}
${a.startDate || ""} - ${a.endDate || "Present"}

- ${xyz}`;
  })
  .join("\n\n")}

## Skills
${Array.from(
  new Set([
    ...(job.requiredSkills || []),
    ...selectedAchievements.flatMap((a) => {
      const text = `${a.situation} ${a.task} ${a.action} ${a.result}`;
      return (job.requiredSkills || []).filter((skill) =>
        text.toLowerCase().includes(skill.toLowerCase())
      );
    }),
  ])
).join(" • ")}

---
*Tailored for ${job.companyName} - Generated by Careerswarm*`;

  // Extract keywords
  const keywords = Array.from(
    new Set([
      ...(job.requiredSkills || []),
      ...(job.preferredSkills || []),
      job.title,
      job.companyName,
    ])
  );

  // Calculate ATS score (simple keyword matching)
  const resumeLower = resumeContent.toLowerCase();
  const matchedKeywords = keywords.filter((kw) =>
    resumeLower.includes(kw.toLowerCase())
  );
  const atsScore = Math.round((matchedKeywords.length / keywords.length) * 100);

  return {
    selectedAchievements: selectedIds,
    resumeContent,
    keywords,
    atsScore,
  };
}
