import { describe, it, expect } from "vitest";

describe("Resume Tailor Logic", () => {
  describe("Achievement Selection", () => {
    it("should select 5-7 achievements from pool", () => {
      const selectedIds = [1, 2, 3, 4, 5, 6];
      expect(selectedIds.length).toBeGreaterThanOrEqual(5);
      expect(selectedIds.length).toBeLessThanOrEqual(7);
    });

    it("should prioritize achievements with higher impact scores", () => {
      const achievements = [
        { id: 1, impactMeterScore: 90 },
        { id: 2, impactMeterScore: 50 },
        { id: 3, impactMeterScore: 80 },
      ];
      
      const sorted = achievements.sort((a, b) => b.impactMeterScore - a.impactMeterScore);
      expect(sorted[0].impactMeterScore).toBe(90);
      expect(sorted[1].impactMeterScore).toBe(80);
    });
  });

  describe("Match Score Calculation", () => {
    it("should return score between 0 and 100", () => {
      const score = 85;
      expect(score).toBeGreaterThanOrEqual(0);
      expect(score).toBeLessThanOrEqual(100);
    });

    it("should classify scores correctly", () => {
      const getLabel = (score: number) => {
        if (score >= 80) return "Excellent Match";
        if (score >= 60) return "Good Match";
        return "Needs Improvement";
      };

      expect(getLabel(90)).toBe("Excellent Match");
      expect(getLabel(70)).toBe("Good Match");
      expect(getLabel(40)).toBe("Needs Improvement");
    });
  });

  describe("Gap Analysis", () => {
    it("should identify missing keywords", () => {
      const jdKeywords = ["Python", "AWS", "Docker", "Kubernetes"];
      const profileKeywords = ["Python", "AWS"];
      
      const missing = jdKeywords.filter(k => !profileKeywords.includes(k));
      expect(missing).toEqual(["Docker", "Kubernetes"]);
    });

    it("should handle case when no keywords are missing", () => {
      const jdKeywords = ["Python", "AWS"];
      const profileKeywords = ["Python", "AWS", "Docker"];
      
      const missing = jdKeywords.filter(k => !profileKeywords.includes(k));
      expect(missing).toEqual([]);
    });
  });

  describe("Professional Summary Generation", () => {
    it("should generate summary with role-specific language", () => {
      const summary = "Experienced Software Engineer with 5 years of expertise in full-stack development.";
      expect(summary).toContain("Software Engineer");
      expect(summary.length).toBeGreaterThan(50);
    });

    it("should be 2-3 sentences long", () => {
      const summary = "First sentence. Second sentence. Third sentence.";
      const sentenceCount = summary.split(". ").length;
      expect(sentenceCount).toBeGreaterThanOrEqual(2);
      expect(sentenceCount).toBeLessThanOrEqual(3);
    });
  });

  describe("Input Validation", () => {
    it("should require job description with minimum length", () => {
      const shortJD = "Software Engineer";
      const longJD = "We are looking for an experienced Software Engineer with 5+ years of experience in Python and AWS.";
      
      expect(shortJD.length).toBeLessThan(50);
      expect(longJD.length).toBeGreaterThanOrEqual(50);
    });

    it("should require job title and company", () => {
      const input = {
        jobTitle: "Software Engineer",
        company: "Google",
        jobDescription: "Long description here...",
      };
      
      expect(input.jobTitle.length).toBeGreaterThanOrEqual(2);
      expect(input.company.length).toBeGreaterThanOrEqual(2);
    });

    it("should reject empty achievements pool", () => {
      const achievements: any[] = [];
      expect(achievements.length).toBe(0);
      // In actual code, this should throw an error
    });
  });

  describe("Resume Content Generation", () => {
    it("should include professional summary", () => {
      const resumeContent = `# John Doe
john@example.com

## Professional Summary
Experienced engineer with proven track record.

## Professional Experience
...`;
      
      expect(resumeContent).toContain("Professional Summary");
    });

    it("should include selected achievements in STAR format", () => {
      const resumeContent = `### Senior Engineer at Google
2020 - Present

- **Situation:** Team needed to improve performance
- **Task:** Reduce API latency by 50%
- **Action:** Implemented caching layer
- **Result:** Achieved 60% latency reduction`;
      
      expect(resumeContent).toContain("Situation:");
      expect(resumeContent).toContain("Task:");
      expect(resumeContent).toContain("Action:");
      expect(resumeContent).toContain("Result:");
    });

    it("should include match score in footer", () => {
      const resumeContent = "...Generated by Careerswarm - Match Score: 85%";
      expect(resumeContent).toContain("Match Score:");
    });
  });

  describe("JSON Response Parsing", () => {
    it("should parse valid JSON response", () => {
      const jsonResponse = JSON.stringify({
        selectedAchievementIds: [1, 2, 3],
        matchScore: 85,
        missingKeywords: ["Docker"],
        professionalSummary: "Experienced engineer...",
      });
      
      const parsed = JSON.parse(jsonResponse);
      expect(parsed.selectedAchievementIds).toHaveLength(3);
      expect(parsed.matchScore).toBe(85);
    });

    it("should handle JSON with markdown code blocks", () => {
      const responseWithMarkdown = '```json\n{"matchScore": 85}\n```';
      const cleaned = responseWithMarkdown.replace(/```json\n?|```\n?/g, "").trim();
      const parsed = JSON.parse(cleaned);
      expect(parsed.matchScore).toBe(85);
    });

    it("should validate required fields", () => {
      const validResponse = {
        selectedAchievementIds: [1, 2, 3],
        matchScore: 85,
        missingKeywords: [],
        professionalSummary: "Summary",
      };
      
      expect(validResponse.selectedAchievementIds).toBeDefined();
      expect(Array.isArray(validResponse.selectedAchievementIds)).toBe(true);
    });

    it("should reject invalid response structure", () => {
      const invalidResponse = {
        matchScore: 85,
        // missing selectedAchievementIds
      };
      
      expect(invalidResponse.selectedAchievementIds).toBeUndefined();
    });
  });
});
